name: Deployment

on:
  push:
    branches: ["feature/5/deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Set up Node # Node 버전 setup
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: ./react-main/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lcok.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./react-main/build
