name: Deployment

on:
  push:
    branches: ["feature/5/deploy"]

jobs:
  deploy:
    name: Build, Deploy
    runs-on: ubuntu-latest
    env:
      working-directory: ./react-main # working directory 지정하기

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout source code # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }} # Node.js 버전 setup
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lcok.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: npm run build
        env:
          CI: false
          NODE_ENV: production
        working-directory: ${{ env.working-directory }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.deploy }}
          publish_dir: ./react-main/build
